name: golangci-lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Setup Rust
        run: (sudo apt-get update && sudo apt-get install -y clang libssl-dev && which cargo && which rustc) || (curl https://sh.rustup.rs -sSf | sh -s -- -y)

      - name: install deps
        run: sudo apt-get install make ftp mesa-opencl-icd ocl-icd-opencl-dev git bzr jq pkg-config curl clang build-essential hwloc libhwloc-dev wget -y && sudo apt upgrade -y

      - name: Make dep
        run: |
          git submodule update --init --recursive
          cd extern/filecoin-ffi && ./install-filcrypto

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v1.44.2
          args: --timeout=30m --skip-dirs='[extern]'
          skip-pkg-cache: true
          skip-build-cache: true
